version: '3.8'

services:
  thesis_app_tiny_mongo:
    build: .
    container_name: thesis_app_tiny_mongo
    ports:
      - "8501:8501" # access via http://localhost:8501
    environment:
      - MONGO_URI=mongodb://mongo:27017
    depends_on:
      - mongo
      - neo4j
    volumes:
      - ~/.ollama/models:/root/.ollama/models  # Use host's cached LLM model

  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017" # access vi