version: '3.8'

services:
  thesis_app_tiny_mongo:
    build: .
    container_name: thesis_app_tiny_mongo
    ports:
      - "8501:8501" # access via http://localhost:8501
    environment:
      - MONGO_URI=mongodb://mongo:27017
    depends_on:
      - mongo
      - neo4j
    volumes:
      - ~/.ollama/models:/root/.ollama/models  # Use host's cached LLM model

  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017" # access via mongodb://localhost:27017 (in Compass)
    volumes:
      - mongo_data:/data/db

  neo4j:
    image: neo4j:5.19-community
    container_name: neo4j
    ports:
      - "7474:7474"   # HTTP browser: access via http://localhost:7474
      - "7687:7687"   # Bolt protocol
    environment:
      - NEO4J_AUTH=${NEO4J_AUTH}
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs

volumes:
  mongo_data:
  neo4j_data:
  neo4j_logs: